package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.TypeKindVisitor9;
import javax.lang.model.type.NoType;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TypeKindVisitor9}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link TypeKindVisitor9} is an old class but has new fields, constructors or methods.
 * @since 9
 * @see TypeKindVisitor9
 */
public final class WhatIsNewInTypeKindVisitor9<R, P>
{
  /**
   * Example call to new method {@link TypeKindVisitor9#visitNoTypeAsModule(NoType, Object)}.
   * @since 10
   * @see TypeKindVisitor9#visitNoTypeAsModule(NoType, Object)
   */
  public R visitNoTypeAsModule(NoType t, P p)
  {
    TypeKindVisitor9<R, P> testee = $$$();

    R result = testee.visitNoTypeAsModule(t, p);
    return result;
  }

  private TypeKindVisitor9<R, P> $$$()
  {
    return null;
  }
}
