package whatisnewin.com.sun.source.doctree;

import com.sun.source.doctree.DocTreeVisitor;
import com.sun.source.doctree.SummaryTree;
import com.sun.source.doctree.DocTypeTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link DocTreeVisitor}
 * that were newly introduced in Java versions 10.<br>
 *
 * {@link DocTreeVisitor} is an old class but has new fields, constructors or methods
 * @since 1.8
 * @see DocTreeVisitor
 */
public final class WhatIsNewInDocTreeVisitor<R, P>
{
  /**
   * Example call to new method {@link DocTreeVisitor#visitSummary}
   * @since 10
   * @see DocTreeVisitor#visitSummary
   */
  public R visitSummary(SummaryTree node, P p)
  {
    DocTreeVisitor<R, P> testee = $$$();

    R result = testee.visitSummary(node, p);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeVisitor#visitDocType}
   * @since 10
   * @see DocTreeVisitor#visitDocType
   */
  public R visitDocType(DocTypeTree node, P p)
  {
    DocTreeVisitor<R, P> testee = $$$();

    R result = testee.visitDocType(node, p);
    return result;
  }

  private DocTreeVisitor $$$()
  {
    return null;
  }
}
