package whatisnewin.java.lang;

import java.lang.Runtime.Version;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Version}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link Version} is an old class but has new fields, constructors or methods.
 * @since 9
 * @see Version
 */
public final class WhatIsNewInRuntime$Version
{
  /**
   * Example call to new method {@link Version#update()}.
   * @since 10
   * @see Version#update()
   */
  public int update()
  {
    Version testee = $$$();

    int result = testee.update();
    return result;
  }

  /**
   * Example call to new method {@link Version#patch()}.
   * @since 10
   * @see Version#patch()
   */
  public int patch()
  {
    Version testee = $$$();

    int result = testee.patch();
    return result;
  }

  /**
   * Example call to new method {@link Version#interim()}.
   * @since 10
   * @see Version#interim()
   */
  public int interim()
  {
    Version testee = $$$();

    int result = testee.interim();
    return result;
  }

  /**
   * Example call to new method {@link Version#feature()}.
   * @since 10
   * @see Version#feature()
   */
  public int feature()
  {
    Version testee = $$$();

    int result = testee.feature();
    return result;
  }

  private Version $$$()
  {
    return null;
  }
}
