package whatisnewin.java.lang;

import java.lang.StackWalker.StackFrame;
import java.lang.invoke.MethodType;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link StackFrame}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link StackFrame} is an old class but has new fields, constructors or methods.
 * @since 9
 * @see StackFrame
 */
public final class WhatIsNewInStackWalker$StackFrame
{
  /**
   * Example call to new method {@link StackFrame#getMethodType()}.
   * @since 10
   * @see StackFrame#getMethodType()
   */
  public MethodType getMethodType()
  {
    StackFrame testee = $$$();

    MethodType result = testee.getMethodType();
    return result;
  }

  /**
   * Example call to new method {@link StackFrame#getDescriptor()}.
   * @since 10
   * @see StackFrame#getDescriptor()
   */
  public String getDescriptor()
  {
    StackFrame testee = $$$();

    String result = testee.getDescriptor();
    return result;
  }

  private StackFrame $$$()
  {
    return null;
  }
}
