package whatisnewin.java.util;

import java.util.List;
import java.util.Collection;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link List}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link List} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see List
 */
public final class WhatIsNewInList<E>
{
  /**
   * Example call to new method {@link List#copyOf(Collection)}.
   * @since 10
   * @see List#copyOf(Collection)
   */
  public static <E> List<E> copyOf(Collection<? extends E> coll)
  {
    List<E> result = List.copyOf(coll);
    return result;
  }

}
