package whatisnewin.java.util;

import java.util.Optional;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Optional}
 * that were newly introduced in Java versions 10.<br>
 *
 * {@link Optional} is an old class but has new fields, constructors or methods
 * @since 1.8
 * @see Optional
 */
public final class WhatIsNewInOptional<T>
{
  /**
   * Example call to new method {@link Optional#orElseThrow}
   * @since 10
   * @see Optional#orElseThrow
   */
  public T orElseThrow()
  {
    Optional<T> testee = $$$();

    T result = testee.orElseThrow();
    return result;
  }

  private Optional $$$()
  {
    return null;
  }
}
