package whatisnewin.java.util;

import java.util.OptionalLong;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OptionalLong}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link OptionalLong} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see OptionalLong
 */
public final class WhatIsNewInOptionalLong
{
  /**
   * Example call to new method {@link OptionalLong#orElseThrow()}.
   * @since 10
   * @see OptionalLong#orElseThrow()
   */
  public long orElseThrow()
  {
    OptionalLong testee = $$$();

    long result = testee.orElseThrow();
    return result;
  }

  private OptionalLong $$$()
  {
    return null;
  }
}
