package whatisnewin.java.util;

import java.util.Map;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Map}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link Map} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see Map
 */
public final class WhatIsNewInMap<K, V>
{
  /**
   * Example call to new method {@link Map#copyOf(Map)}.
   * @since 10
   * @see Map#copyOf(Map)
   */
  public static <K, V> Map<K, V> copyOf(Map<? extends K, ? extends V> map)
  {
    Map<K, V> result = Map.copyOf(map);
    return result;
  }

}
