package whatisnewin.java.util;

import java.util.OptionalInt;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OptionalInt}
 * that were newly introduced in Java version 10.<br>
 *
 * {@link OptionalInt} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see OptionalInt
 */
public final class WhatIsNewInOptionalInt
{
  /**
   * Example call to new method {@link OptionalInt#orElseThrow()}.
   * @since 10
   * @see OptionalInt#orElseThrow()
   */
  public int orElseThrow()
  {
    OptionalInt testee = $$$();

    int result = testee.orElseThrow();
    return result;
  }

  private OptionalInt $$$()
  {
    return null;
  }
}
