package whatisnewin.com.sun.source.util;

import com.sun.source.util.DocTreeFactory;
import com.sun.source.doctree.DocTypeTree;
import com.sun.source.doctree.DocCommentTree;
import java.util.List;
import com.sun.source.doctree.DocTree;
import com.sun.source.doctree.SummaryTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link DocTreeFactory}
 * that were newly introduced in Java versions 10.<br>
 *
 * {@link DocTreeFactory} is an old class but has new fields, constructors or methods
 * @since 9
 * @see DocTreeFactory
 */
public final class WhatIsNewInDocTreeFactory
{
  /**
   * Example call to new method {@link DocTreeFactory#newDocTypeTree}
   * @since 10
   * @see DocTreeFactory#newDocTypeTree
   */
  public DocTypeTree newDocTypeTree(String text)
  {
    DocTreeFactory testee = $$$();

    DocTypeTree result = testee.newDocTypeTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocCommentTree}
   * @since 10
   * @see DocTreeFactory#newDocCommentTree
   */
  public DocCommentTree newDocCommentTree(List<? extends DocTree> fullBody, List<? extends DocTree> tags, List<? extends DocTree> preamble, List<? extends DocTree> postamble)
  {
    DocTreeFactory testee = $$$();

    DocCommentTree result = testee.newDocCommentTree(fullBody, tags, preamble, postamble);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSummaryTree}
   * @since 10
   * @see DocTreeFactory#newSummaryTree
   */
  public SummaryTree newSummaryTree(List<? extends DocTree> summary)
  {
    DocTreeFactory testee = $$$();

    SummaryTree result = testee.newSummaryTree(summary);
    return result;
  }

  private DocTreeFactory $$$()
  {
    return null;
  }
}
